# Cors
allow_cors_origins = ["https://backendery.io", "https://*.backendery.io", "http://localhost"]

# Email's
from_mailbox = "Backendery <hey@backendery.io>"
to_mailbox = "Backendery <hey@backendery.io>"

# Retry
retry_count = 2
retry_timeout = 50

# Router
concurrency_limit = 64

# Smpt
smtp_connection_timeout = 5000
